services:    
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PW}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - webme-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal

volumes:
  webme-data:

networks:
  internal:
