name: Deploy latest webMe

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: [self-hosted, linux, X64]
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Pull latest code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env << EOF
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GITHUB_ID=${{ secrets.GH_ID }}
          GITHUB_SECRET=${{ secrets.GH_SECRET }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PW=${{ secrets.DATABASE_PW }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          EOF

      - name: Install dependencies
        run: npm ci

      - name: Run database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Update container with docker compose
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build